export const unit08Additions = {
  unit: {
    id: 'UNIT_08',
    label: 'Unit 8',
    title: 'DC Motor Control',
    desc: 'Control motors precisely with setPower(), setDirection(), ZeroPowerBehavior, and software limit switches.',
    tier: 'Intermediate',
    slug: 'unit-08',
    overviewPath: '/docs/unit-08',
    startPath: '/docs/unit-08/set-power',
    nextPath: '/dashboard',
    nextLabel: 'Dashboard',
    lessonCount: 6,
  },
  lessons: [
    {
      id: 'unit-08/set-power',
      label: '8.1 · setPower()',
      title: 'Lesson 8.1: Applying Voltage to Motors with the setPower() Method',
      path: '/docs/unit-08/set-power',
      unitSlug: 'unit-08',
      unitLabel: 'Unit 8',
      unitTitle: 'DC Motor Control',
    },
    {
      id: 'unit-08/set-direction',
      label: '8.2 · setDirection()',
      title: 'Lesson 8.2: Reversing Mechanical Bias using setDirection(REVERSE)',
      path: '/docs/unit-08/set-direction',
      unitSlug: 'unit-08',
      unitLabel: 'Unit 8',
      unitTitle: 'DC Motor Control',
    },
    {
      id: 'unit-08/zero-power-behavior',
      label: '8.3 · ZeroPowerBehavior',
      title: 'Lesson 8.3: Managing Backlash with ZeroPowerBehavior.BRAKE',
      path: '/docs/unit-08/zero-power-behavior',
      unitSlug: 'unit-08',
      unitLabel: 'Unit 8',
      unitTitle: 'DC Motor Control',
    },
    {
      id: 'unit-08/coast-vs-stop',
      label: '8.4 · Coast vs. Stop',
      title: 'Lesson 8.4: Utilizing setPower(0.0) for Consistent Coast vs. Stop Behavior',
      path: '/docs/unit-08/coast-vs-stop',
      unitSlug: 'unit-08',
      unitLabel: 'Unit 8',
      unitTitle: 'DC Motor Control',
    },
    {
      id: 'unit-08/linear-slide-challenge',
      label: '8.5 · Challenge: Linear Slide',
      title: 'Lesson 8.5: Challenge — Creating a Bidirectional Linear Slide Control with Software Limiters',
      path: '/docs/unit-08/linear-slide-challenge',
      unitSlug: 'unit-08',
      unitLabel: 'Unit 8',
      unitTitle: 'DC Motor Control',
    },
    {
      id: 'unit-08/mastery-quiz',
      label: 'Unit 8 · Mastery Quiz',
      title: 'Unit 8 Mastery Quiz: DC Motor Control',
      path: '/docs/unit-08/mastery-quiz',
      unitSlug: 'unit-08',
      unitLabel: 'Unit 8',
      unitTitle: 'DC Motor Control',
    },
  ],
  notes: {
    previousUnitQuiz: {
      lessonId: 'unit-07/mastery-quiz',
      nextUnit: '/docs/unit-08',
      nextUnitName: 'Unit 8: DC Motor Control',
    },
  },
} as const;
