export const unit07Additions = {
  unit: {
    id: 'UNIT_07',
    label: 'Unit 7',
    title: 'Hardware Mapping',
    desc: 'Master the hardwareMap registry, DcMotor and sensor instantiation, name-mismatch debugging, and reusable mechanism classes.',
    tier: 'Intermediate',
    slug: 'unit-07',
    overviewPath: '/docs/unit-07',
    startPath: '/docs/unit-07/hardware-map-object',
    nextPath: '/docs/unit-08',
    nextLabel: 'Unit 8: DC Motor Control',
    lessonCount: 6,
  },
  lessons: [
    {
      id: 'unit-07/hardware-map-object',
      label: '7.1 · hardwareMap Object',
      title: 'Lesson 7.1: Accessing the Configuration Registry via the hardwareMap Object',
      path: '/docs/unit-07/hardware-map-object',
      unitSlug: 'unit-07',
      unitLabel: 'Unit 7',
      unitTitle: 'Hardware Mapping',
    },
    {
      id: 'unit-07/dcmotor-mapping',
      label: '7.2 · DcMotor Mapping',
      title: 'Lesson 7.2: Registering DcMotors and Assigning Port-Specific Names',
      path: '/docs/unit-07/dcmotor-mapping',
      unitSlug: 'unit-07',
      unitLabel: 'Unit 7',
      unitTitle: 'Hardware Mapping',
    },
    {
      id: 'unit-07/sensor-mapping',
      label: '7.3 · Sensor Mapping',
      title: 'Lesson 7.3: Instantiating Digital and Analog Sensor Objects in Java',
      path: '/docs/unit-07/sensor-mapping',
      unitSlug: 'unit-07',
      unitLabel: 'Unit 7',
      unitTitle: 'Hardware Mapping',
    },
    {
      id: 'unit-07/name-mismatches',
      label: '7.4 · Name Mismatches',
      title: 'Lesson 7.4: Troubleshooting Name Mismatches and Configuration Overlays',
      path: '/docs/unit-07/name-mismatches',
      unitSlug: 'unit-07',
      unitLabel: 'Unit 7',
      unitTitle: 'Hardware Mapping',
    },
    {
      id: 'unit-07/mechanism-classes',
      label: '7.5 · Challenge: Mechanism Classes',
      title: 'Lesson 7.5: Challenge — Synchronizing Hardware Classes Across Multiple OpModes',
      path: '/docs/unit-07/mechanism-classes',
      unitSlug: 'unit-07',
      unitLabel: 'Unit 7',
      unitTitle: 'Hardware Mapping',
    },
    {
      id: 'unit-07/mastery-quiz',
      label: 'Unit 7 · Mastery Quiz',
      title: 'Unit 7 Mastery Quiz: Hardware Mapping',
      path: '/docs/unit-07/mastery-quiz',
      unitSlug: 'unit-07',
      unitLabel: 'Unit 7',
      unitTitle: 'Hardware Mapping',
    },
  ],
  notes: {
    previousUnitQuiz: {
      lessonId: 'unit-06/mastery-quiz',
      nextUnit: '/docs/unit-07',
      nextUnitName: 'Unit 7: Hardware Mapping',
    },
  },
} as const;
