export type Tier = 'Beginner' | 'Intermediate' | 'Advanced';

export interface CurriculumUnit {
  id: string;
  label: string;
  title: string;
  desc: string;
  tier: Tier;
  slug: string;
  overviewPath: string;
  startPath: string;
  nextPath: string;
  nextLabel: string;
  lessonCount: number;
  overview: string;
  outcomes: string[];
}

export interface CurriculumLesson {
  id: string;
  label: string;
  title: string;
  path: string;
  unitSlug: string;
  unitLabel: string;
  unitTitle: string;
}

export const CURRICULUM_UNITS: CurriculumUnit[] = [
  {
    id: 'UNIT_01',
    label: 'Unit 1',
    title: 'Environment Setup',
    desc: 'Install JDK 17, Android Studio, and the FTC SDK, then verify the toolchain.',
    tier: 'Beginner',
    slug: 'unit-01',
    overviewPath: '/docs/unit-01',
    startPath: '/docs/unit-01/prerequisites',
    nextPath: '/docs/unit-02',
    nextLabel: 'Unit 2: OpMode Structure',
    lessonCount: 10,
    overview:
      'This unit gets every student onto the same stable FTC development setup before any robot code is written.',
    outcomes: [
      'Install JDK 17 and Android Studio with the right FTC-compatible settings.',
      'Clone and open the FTC SDK without Gradle or build configuration issues.',
      'Verify that your environment can build and deploy a basic diagnostic OpMode.',
    ],
  },
  {
    id: 'UNIT_02',
    label: 'Unit 2',
    title: 'OpMode Structure',
    desc: 'Learn annotations plus the init(), loop(), start(), and stop() lifecycle.',
    tier: 'Beginner',
    slug: 'unit-02',
    overviewPath: '/docs/unit-02',
    startPath: '/docs/unit-02/registering-programs',
    nextPath: '/docs/unit-03',
    nextLabel: 'Unit 3: Java Variables',
    lessonCount: 6,
    overview:
      'This unit introduces the FTC OpMode lifecycle so students understand where initialization, real-time control, and one-time transitions belong.',
    outcomes: [
      'Choose the right annotation so programs appear correctly on the Driver Station.',
      'Separate setup work from repeated loop logic and one-time start/stop transitions.',
      'Build a health-check style OpMode that reports robot state clearly through telemetry.',
    ],
  },
  {
    id: 'UNIT_03',
    label: 'Unit 3',
    title: 'Java Variables',
    desc: 'Practice String, double, boolean, and int patterns in FTC robot code.',
    tier: 'Beginner',
    slug: 'unit-03',
    overviewPath: '/docs/unit-03',
    startPath: '/docs/unit-03/string-literals',
    nextPath: '/docs/unit-04',
    nextLabel: 'Unit 4: Gamepad Input',
    lessonCount: 6,
    overview:
      'This unit focuses on the Java datatypes students will use constantly when mapping hardware, reading sensors, and calculating robot behavior.',
    outcomes: [
      'Choose the correct datatype for names, numeric precision, binary state, and whole-number counts.',
      'Avoid common FTC bugs caused by integer truncation or mismatched hardware identifiers.',
      'Use variables as a single source of truth instead of scattering magic values through code.',
    ],
  },
  {
    id: 'UNIT_04',
    label: 'Unit 4',
    title: 'Gamepad Input',
    desc: 'Map buttons, joysticks, and triggers to robot mechanisms with deadzones and sensitivity curves.',
    tier: 'Beginner',
    slug: 'unit-04',
    overviewPath: '/docs/unit-04',
    startPath: '/docs/unit-04/button-toggles',
    nextPath: '/docs/unit-05',
    nextLabel: 'Unit 5: Logic & Decisions',
    lessonCount: 6,
    overview:
      'This unit teaches students how driver input gets translated into robot behavior, from simple button toggles to analog control shaping.',
    outcomes: [
      'Use buttons, joysticks, and triggers appropriately based on whether the mechanism needs digital or analog control.',
      'Implement deadzones and sensitivity shaping so the robot feels stable and intuitive to drive.',
      'Combine multiple gamepad inputs into a clean arcade-drive style control system.',
    ],
  },
  {
    id: 'UNIT_05',
    label: 'Unit 5',
    title: 'Logic & Decisions',
    desc: 'Use if statements, else if chains, comparison operators, and logical AND/OR for hardware safety gates.',
    tier: 'Beginner',
    slug: 'unit-05',
    overviewPath: '/docs/unit-05',
    startPath: '/docs/unit-05/if-statements',
    nextPath: '/docs/unit-06',
    nextLabel: 'Unit 6: Loops & Iteration',
    lessonCount: 6,
    overview:
      'This unit builds the decision-making layer of robot code — from simple button checks to multi-sensor logic trees that automate game element sorting.',
    outcomes: [
      'Use if/else if/else chains to guarantee a single unambiguous command reaches hardware each loop cycle.',
      'Implement comparison operators to create soft-limit safety zones that prevent motors from exceeding physical bounds.',
      'Combine multiple sensor thresholds with logical AND/OR operators for robust, driver-verified hardware actions.',
    ],
  },
  {
    id: 'UNIT_06',
    label: 'Unit 6',
    title: 'Loops & Iteration',
    desc: 'Master while(opModeIsActive()), for loops, getRuntime() timing, hardware arrays, and non-blocking parallel control.',
    tier: 'Intermediate',
    slug: 'unit-06',
    overviewPath: '/docs/unit-06',
    startPath: '/docs/unit-06/opmode-active',
    nextPath: '/docs/unit-07',
    nextLabel: 'Unit 7: Hardware Mapping',
    lessonCount: 6,
    overview:
      'This unit moves students from one-shot commands into repeated execution, timing control, and scalable iteration patterns for real FTC robots.',
    outcomes: [
      'Use loop-based control structures safely so code stops when the OpMode stops.',
      'Automate repeated actions and multi-device commands with for loops and array iteration.',
      'Build timer-based behavior that runs in parallel without freezing the rest of the robot.',
    ],
  },
  {
    id: 'UNIT_07',
    label: 'Unit 7',
    title: 'Hardware Mapping',
    desc: 'Master the hardwareMap registry, DcMotor and sensor instantiation, name-mismatch debugging, and reusable mechanism classes.',
    tier: 'Intermediate',
    slug: 'unit-07',
    overviewPath: '/docs/unit-07',
    startPath: '/docs/unit-07/hardware-map-object',
    nextPath: '/docs/unit-08',
    nextLabel: 'Unit 8: DC Motor Control',
    lessonCount: 6,
    overview:
      'This unit connects FTC configuration names to Java objects so students can safely instantiate motors, sensors, and reusable mechanisms.',
    outcomes: [
      'Use the hardwareMap registry to retrieve configured devices with the correct Java class and exact robot configuration name.',
      'Map motors and sensors consistently while diagnosing name mismatches and configuration overlay problems quickly.',
      'Organize shared mechanism code into reusable classes that stay synchronized across multiple OpModes.',
    ],
  },
  {
    id: 'UNIT_08',
    label: 'Unit 8',
    title: 'DC Motor Control',
    desc: 'Control motors precisely with setPower(), setDirection(), ZeroPowerBehavior, and software limit switches.',
    tier: 'Intermediate',
    slug: 'unit-08',
    overviewPath: '/docs/unit-08',
    startPath: '/docs/unit-08/set-power',
    nextPath: '/docs/unit-09',
    nextLabel: 'Unit 9: Servo Control',
    lessonCount: 6,
    overview:
      'This unit turns mapped motors into predictable mechanisms by covering power control, direction reversal, braking behavior, and safety-limited motion.',
    outcomes: [
      'Apply motor power intentionally with setPower() so mechanisms move at the right speed and stop when expected.',
      'Correct mechanical orientation issues with setDirection() and choose between coasting and braking behavior deliberately.',
      'Build safer motor routines with zero-power handling and software-enforced motion limits for mechanisms like linear slides.',
    ],
  },
  {
    id: 'UNIT_09',
    label: 'Unit 9',
    title: 'Servo Control',
    desc: 'Command positional servos with setPosition(), scaleRange(), and setDirection(), and control continuous rotation servos for intake mechanisms.',
    tier: 'Intermediate',
    slug: 'unit-09',
    overviewPath: '/docs/unit-09',
    startPath: '/docs/unit-09/set-position',
    nextPath: '/dashboard',
    nextLabel: 'Dashboard',
    lessonCount: 6,
    overview:
      'This unit extends mechanism control beyond DC motors by teaching students how to command standard and continuous rotation servos safely and predictably.',
    outcomes: [
      'Use setPosition() and scaleRange() to command positional servos without overdriving physical linkages.',
      'Configure mirrored mechanisms cleanly with servo direction settings instead of duplicating inversion math across OpModes.',
      'Choose correctly between Servo and CRServo so intake and gripper mechanisms use the right control model.',
    ],
  },
];

export const CURRICULUM_LESSONS: CurriculumLesson[] = [
  {
    id: 'unit-01/prerequisites',
    label: '1 · Prerequisites',
    title: 'Section 1: What You Need Before You Start',
    path: '/docs/unit-01/prerequisites',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/install-jdk',
    label: '2 · Installing JDK 17',
    title: 'Section 2: Installing JDK 17',
    path: '/docs/unit-01/install-jdk',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/install-android-studio',
    label: '3 · Installing Android Studio',
    title: 'Section 3: Installing Android Studio',
    path: '/docs/unit-01/install-android-studio',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/configure-jdk',
    label: '4 · Configure JDK',
    title: 'Section 4: Pointing Android Studio to JDK 17',
    path: '/docs/unit-01/configure-jdk',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/get-ftc-sdk',
    label: '5 · Getting the FTC SDK',
    title: 'Section 5: Getting the FTC SDK',
    path: '/docs/unit-01/get-ftc-sdk',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/open-project',
    label: '6 · Open the Project',
    title: 'Section 6: Opening the Project in Android Studio',
    path: '/docs/unit-01/open-project',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/verify-build-config',
    label: '7 · Verify Build Config',
    title: 'Section 7: Verifying the Build Configuration',
    path: '/docs/unit-01/verify-build-config',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/first-opmode',
    label: '8 · First OpMode',
    title: 'Section 8: Writing Your First OpMode',
    path: '/docs/unit-01/first-opmode',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/connect-control-hub',
    label: '9 · Connect to Control Hub',
    title: 'Section 9: Connecting to the Control Hub',
    path: '/docs/unit-01/connect-control-hub',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/verification-checklist',
    label: '10 · Verification Checklist',
    title: 'Section 10: Environment Verification Checklist',
    path: '/docs/unit-01/verification-checklist',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-02/registering-programs',
    label: '2.1 · @TeleOp & @Autonomous',
    title: 'Lesson 2.1: Registering Programs with @TeleOp and @Autonomous Annotations',
    path: '/docs/unit-02/registering-programs',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/init-method',
    label: '2.2 · init() Method',
    title: 'Lesson 2.2: Initializing Peripheral Hardware within the init() Method',
    path: '/docs/unit-02/init-method',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/loop-lifecycle',
    label: '2.3 · loop() Lifecycle',
    title: 'Lesson 2.3: Executing Real-time Logic inside the loop() Lifecycle',
    path: '/docs/unit-02/loop-lifecycle',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/start-and-stop',
    label: '2.4 · start() & stop()',
    title: 'Lesson 2.4: Utilizing start() and stop() for One-time Hardware Transitions',
    path: '/docs/unit-02/start-and-stop',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/health-check-challenge',
    label: '2.5 · Challenge: Health-Check',
    title: 'Lesson 2.5: Challenge — Implementing a Robot Health-Check OpMode with Telemetry Feedback',
    path: '/docs/unit-02/health-check-challenge',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/mastery-quiz',
    label: 'Unit 2 · Mastery Quiz',
    title: 'Unit 2 Mastery Quiz: OpMode Structure',
    path: '/docs/unit-02/mastery-quiz',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-03/string-literals',
    label: '3.1 · String Literals',
    title: 'Lesson 3.1: Using String Literals for Exact Hardware Configuration Names',
    path: '/docs/unit-03/string-literals',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/double-precision',
    label: '3.2 · double Precision',
    title: 'Lesson 3.2: Storing Motor Power Levels with double Precision',
    path: '/docs/unit-03/double-precision',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/boolean-flags',
    label: '3.3 · boolean Flags',
    title: 'Lesson 3.3: Managing Binary Sensor States using boolean Flags',
    path: '/docs/unit-03/boolean-flags',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/int-datatypes',
    label: '3.4 · int Datatypes',
    title: 'Lesson 3.4: Tracking Mechanism Cycle Counts with int Datatypes',
    path: '/docs/unit-03/int-datatypes',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/dynamic-power-challenge',
    label: '3.5 · Challenge: Dynamic Power',
    title: 'Lesson 3.5: Challenge — Dynamic Power Calculation using Multi-Variable Math Operations',
    path: '/docs/unit-03/dynamic-power-challenge',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/mastery-quiz',
    label: 'Unit 3 · Mastery Quiz',
    title: 'Unit 3 Mastery Quiz: Java Variables',
    path: '/docs/unit-03/mastery-quiz',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-04/button-toggles',
    label: '4.1 · Button Toggles',
    title: 'Lesson 4.1: Mapping gamepad.a and gamepad.b to Direct Mechanism Toggles',
    path: '/docs/unit-04/button-toggles',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/joystick-scaling',
    label: '4.2 · Joystick Scaling',
    title: 'Lesson 4.2: Scaling Joystick X/Y Analog Values for Differential Drive',
    path: '/docs/unit-04/joystick-scaling',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/trigger-inputs',
    label: '4.3 · Trigger Inputs',
    title: 'Lesson 4.3: Implementing Progressive Braking via Analog Trigger Inputs',
    path: '/docs/unit-04/trigger-inputs',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/sensitivity-curves',
    label: '4.4 · Sensitivity Curves',
    title: 'Lesson 4.4: Reducing Stick Sensitivity using the squareInputWithSign() Method',
    path: '/docs/unit-04/sensitivity-curves',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/arcade-drive-challenge',
    label: '4.5 · Challenge: Arcade Drive',
    title: 'Lesson 4.5: Challenge — Full Arcade Drive Mapping with Custom Deadzones and Sensitivity Curves',
    path: '/docs/unit-04/arcade-drive-challenge',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/mastery-quiz',
    label: 'Unit 4 · Mastery Quiz',
    title: 'Unit 4 Mastery Quiz: Gamepad Input',
    path: '/docs/unit-04/mastery-quiz',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-05/if-statements',
    label: '5.1 · if Statements',
    title: 'Lesson 5.1: Conditional Motor Activation using Foundational if Statements',
    path: '/docs/unit-05/if-statements',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/else-if-chaining',
    label: '5.2 · else if Chaining',
    title: 'Lesson 5.2: Handling Mutually Exclusive Hardware States with else if Chaining',
    path: '/docs/unit-05/else-if-chaining',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/comparison-operators',
    label: '5.3 · Comparison Operators',
    title: 'Lesson 5.3: Implementing Hardware Safe-Zones with Comparison Operators',
    path: '/docs/unit-05/comparison-operators',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/logical-operators',
    label: '5.4 · Logical Operators',
    title: 'Lesson 5.4: Combining Sensor Thresholds with Logical AND/OR Operators',
    path: '/docs/unit-05/logical-operators',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/intake-logic-challenge',
    label: '5.5 · Challenge: Intake Logic',
    title: 'Lesson 5.5: Challenge — Designing a Multi-Stage Intake Logic Tree for Game Element Sorting',
    path: '/docs/unit-05/intake-logic-challenge',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/mastery-quiz',
    label: 'Unit 5 · Mastery Quiz',
    title: 'Unit 5 Mastery Quiz: Logic & Decisions',
    path: '/docs/unit-05/mastery-quiz',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-06/opmode-active',
    label: '6.1 · opModeIsActive()',
    title: 'Lesson 6.1: Safeguarding Main Execution with while(opModeIsActive())',
    path: '/docs/unit-06/opmode-active',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/for-loops',
    label: '6.2 · for Loops',
    title: 'Lesson 6.2: Automating Repetitive Motion Patterns with for Loops',
    path: '/docs/unit-06/for-loops',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/runtime-timing',
    label: '6.3 · getRuntime() Timing',
    title: 'Lesson 6.3: Managing Timed Transitions using getRuntime() Loop Comparisons',
    path: '/docs/unit-06/runtime-timing',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/hardware-arrays',
    label: '6.4 · Hardware Arrays',
    title: 'Lesson 6.4: Iterating Hardware Arrays using for..each Syntax',
    path: '/docs/unit-06/hardware-arrays',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/nonblocking-timer',
    label: '6.5 · Challenge: Non-Blocking Timer',
    title: 'Lesson 6.5: Challenge — Building a Non-Blocking Timer Loop for Parallel Mechanism Control',
    path: '/docs/unit-06/nonblocking-timer',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/mastery-quiz',
    label: 'Unit 6 · Mastery Quiz',
    title: 'Unit 6 Mastery Quiz: Loops & Iteration',
    path: '/docs/unit-06/mastery-quiz',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-07/hardware-map-object',
    label: '7.1 · hardwareMap Object',
    title: 'Lesson 7.1: Accessing the Configuration Registry via the hardwareMap Object',
    path: '/docs/unit-07/hardware-map-object',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/dcmotor-mapping',
    label: '7.2 · DcMotor Mapping',
    title: 'Lesson 7.2: Registering DcMotors and Assigning Port-Specific Names',
    path: '/docs/unit-07/dcmotor-mapping',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/sensor-mapping',
    label: '7.3 · Sensor Mapping',
    title: 'Lesson 7.3: Instantiating Digital and Analog Sensor Objects in Java',
    path: '/docs/unit-07/sensor-mapping',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/name-mismatches',
    label: '7.4 · Name Mismatches',
    title: 'Lesson 7.4: Troubleshooting Name Mismatches and Configuration Overlays',
    path: '/docs/unit-07/name-mismatches',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/mechanism-classes',
    label: '7.5 · Challenge: Mechanism Classes',
    title: 'Lesson 7.5: Challenge — Synchronizing Hardware Classes Across Multiple OpModes',
    path: '/docs/unit-07/mechanism-classes',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/mastery-quiz',
    label: 'Unit 7 · Mastery Quiz',
    title: 'Unit 7 Mastery Quiz: Hardware Mapping',
    path: '/docs/unit-07/mastery-quiz',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-08/set-power',
    label: '8.1 · setPower()',
    title: 'Lesson 8.1: Applying Voltage to Motors with the setPower() Method',
    path: '/docs/unit-08/set-power',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/set-direction',
    label: '8.2 · setDirection()',
    title: 'Lesson 8.2: Reversing Mechanical Bias using setDirection(REVERSE)',
    path: '/docs/unit-08/set-direction',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/zero-power-behavior',
    label: '8.3 · ZeroPowerBehavior',
    title: 'Lesson 8.3: Managing Backlash with ZeroPowerBehavior.BRAKE',
    path: '/docs/unit-08/zero-power-behavior',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/coast-vs-stop',
    label: '8.4 · Coast vs. Stop',
    title: 'Lesson 8.4: Utilizing setPower(0.0) for Consistent Coast vs. Stop Behavior',
    path: '/docs/unit-08/coast-vs-stop',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/linear-slide-challenge',
    label: '8.5 · Challenge: Linear Slide',
    title: 'Lesson 8.5: Challenge — Creating a Bidirectional Linear Slide Control with Software Limiters',
    path: '/docs/unit-08/linear-slide-challenge',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/mastery-quiz',
    label: 'Unit 8 · Mastery Quiz',
    title: 'Unit 8 Mastery Quiz: DC Motor Control',
    path: '/docs/unit-08/mastery-quiz',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-09/set-position',
    label: '9.1 · setPosition()',
    title: 'Lesson 9.1: Commanding Rotational Precision with setPosition()',
    path: '/docs/unit-09/set-position',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/scale-range',
    label: '9.2 · scaleRange()',
    title: 'Lesson 9.2: Constraining Physical Motion Ranges with scaleRange()',
    path: '/docs/unit-09/scale-range',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/servo-direction',
    label: '9.3 · Servo Direction',
    title: 'Lesson 9.3: Configuring Servo Logical Direction for Inverted Assemblies',
    path: '/docs/unit-09/servo-direction',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/cr-servo',
    label: '9.4 · CRServo',
    title: 'Lesson 9.4: Mapping Continuous Rotation Servos for Intake Mechanisms',
    path: '/docs/unit-09/cr-servo',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/dual-servo-challenge',
    label: '9.5 · Challenge: Dual-Servo Gripper',
    title: 'Lesson 9.5: Challenge — Synchronizing Dual-Servo Grippers with Independent Position Offsets',
    path: '/docs/unit-09/dual-servo-challenge',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/mastery-quiz',
    label: 'Unit 9 · Mastery Quiz',
    title: 'Unit 9 Mastery Quiz: Servo Control',
    path: '/docs/unit-09/mastery-quiz',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
];

export const CURRICULUM_UNIT_COUNT = CURRICULUM_UNITS.length;
export const CURRICULUM_LESSON_COUNT = CURRICULUM_LESSONS.length;

export function getUnitBySlug(unitSlug: string): CurriculumUnit | undefined {
  return CURRICULUM_UNITS.find((unit) => unit.slug === unitSlug);
}

export function getLessonsForUnit(unitSlug: string): CurriculumLesson[] {
  return CURRICULUM_LESSONS.filter((lesson) => lesson.unitSlug === unitSlug);
}
